#!/bin/bash
export CIA_ROOT=/usr/local/cia
export MAC_FILE=/usr/local/cia/config/MAC.conf
export HOSTS_INSTALL=/usr/local/cia/config/hosts.install
export GROUPS_INSTALL=/usr/local/cia/config/groups.install

export INSTALL_DEVICE=eth1
export MASTER_IP=192.168.1.253
export NETMASK=255.255.255.0
export DHCP_CONF=/etc/dhcpd.conf

export CI_ROOT=$CIA_ROOT/cluster_install
export CA_ROOT=$CIA_ROOT/cluster_admin
export CIA_FUNCTIONS=/usr/local/cia/bin/functions

$CA_ROOT/bin/ca_ping $*

